{
    "metadata": {
        "batch": 1517607828,
        "created": "2018-02-02T22:43:48.0220047+01:00"
    },
    "content": {
        "CITY": "New York",
        "CUSTNO": "170748",
        "DOCTYPE": "CREDITNOTE",
        "DATE": "2017-05-18",
        "FIRSTNAME": "Jane",
        "GROSS": "-405.88",
        "LASTNAME": "Doeanne",
        "NET": "-376.00",
        "STREET": "Another Lane 384",
        "ZIP": "10009"
    }
}