language: go
go:
  - "1.8.x"
  - "1.9.x"
  - "1.10.x"
env:
  - GOARCH=amd64
sudo: false
script:
  - wget -O dep https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64
  - chmod +x dep
  - ./dep ensure
  - go test -v ./...
  - ./build-release.sh
