language: go
go:
  - "1.12.x"
  - "1.13.x"
  - "1.14.x"
env:
  - GOARCH=amd64
sudo: required
before_install:
  - sudo apt-get install -y python-pip
  - sudo pip install -U sphinx
  - sudo pip install sphinx_rtd_theme
script:
  - make && make test && ./test/integrationtest.sh
