language: go
go:
  - "1.8.x"
  - "1.9.x"
  - "1.10.x"
env:
  - GOARCH=amd64
sudo: required
before_install:
  - sudo apt-get install -y python-pip
  - sudo pip install -U sphinx
  - sudo pip install sphinx_rtd_theme
script:
  - wget -O dep https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64
  - chmod +x dep
  - ./dep ensure
  - go test ./...
  - ./build-release.sh
