language: go
go:
  - "1.13.x"
  - "1.14.x"
env:
  - GOARCH=amd64
sudo: required
services:
  - docker
before_install:
  - sudo apt-get install -y python-pip
  - sudo pip install -U sphinx
  - sudo pip install sphinx_rtd_theme
script:
  - docker build -t docproc/base -f ./test/dockerfiles/Dockerfile .
  - docker-compose -f ./test/dockerfiles/docker-compose.yml build
  - docker-compose -f ./test/dockerfiles/docker-compose.yml up --abort-on-container-exit
