FROM docproc/base

WORKDIR /app

COPY ./scripts/docproc.startup.sh /bin/docproc.startup.sh
RUN sed -i -e 's/\$APP\$/\/app\/docproc.renderer/g' /bin/docproc.startup.sh
RUN chmod a+x /bin/docproc.startup.sh

# Test data
COPY ./examples/docproc-renderer.conf /app
COPY ./examples/templates/renderer /app/templates/renderer

ENTRYPOINT /bin/docproc.startup.sh
