FROM docproc/base

WORKDIR /app

COPY ./scripts/docproc.startup.sh /bin/docproc.startup.sh
RUN sed -i -e 's/\$APP\$/\/app\/docproc.postproc/g' /bin/docproc.startup.sh
RUN chmod a+x /bin/docproc.startup.sh

# Test data
COPY ./examples/docproc-postproc.conf /app

ENTRYPOINT /bin/docproc.startup.sh
