[[constraint]]
  name = "github.com/google/uuid"
  version = "0.2"

[[constraint]]
  branch = "master"
  name = "github.com/kr/beanstalk"

[[constraint]]
  name = "github.com/nats-io/go-nats"
  version = "1.4.0"

[[constraint]]
  name = "github.com/nsqio/go-nsq"
  version = "1.0.7"

[prune]
  go-tests = true
  unused-packages = true
