FROM docproc/base

WORKDIR /app
RUN mkdir /app/output

COPY ./test/docproc.startup.sh /bin/docproc.startup.sh
RUN sed -i -e 's/\$APP\$/\/app\/bin\/docproc.proc/g' /bin/docproc.startup.sh
RUN chmod a+x /bin/docproc.startup.sh

# Test data
COPY ./examples/docproc-output.conf /app
COPY ./examples/docproc-output.beanstalk.conf /app
COPY ./examples/rules/output /app/rules/output

CMD ["/bin/docproc.startup.sh", "-c", "/app/docproc-output.conf"]
