FROM docproc/base

WORKDIR /app

COPY ./test/docproc.startup.sh /bin/docproc.startup.sh
RUN sed -i -e 's/\$APP\$/\/app\/bin\/docproc.proc/g' /bin/docproc.startup.sh
RUN chmod a+x /bin/docproc.startup.sh

# Test data
COPY ./examples/docproc-preproc.conf /app
COPY ./examples/docproc-preproc.beanstalk.conf /app
COPY ./examples/rules/preproc /app/rules/preproc
COPY ./examples/templates/preproc /app/templates/preproc

CMD ["/bin/docproc.startup.sh", "-c", "/app/docproc-preproc.conf"]
