FROM docproc/base

WORKDIR /app

COPY ./test/docproc.startup.sh /bin/docproc.startup.sh
RUN sed -i -e 's/\$APP\$/\/app\/bin\/docproc.fileinput/g' /bin/docproc.startup.sh
RUN chmod a+x /bin/docproc.startup.sh

# Test data
RUN mkdir /app/data
COPY ./examples/docproc-fileinput.conf /app

ENTRYPOINT /bin/docproc.startup.sh
