FROM docproc/base

WORKDIR /app

COPY ./test/docproc.startup.sh /bin/docproc.startup.sh
RUN sed -i -e 's/\$APP\$/\/app\/bin\/docproc.webinput/g' /bin/docproc.startup.sh
RUN chmod a+x /bin/docproc.startup.sh

# Test data
COPY ./examples/docproc-webinput.conf /app
COPY ./examples/docproc-webinput.beanstalk.conf /app

CMD ["/bin/docproc.startup.sh", "-c", "/app/docproc-webinput.conf"]
